version: '2.0'

volumes:
  portainer_data:

networks:
  linkt_net:
    ipam:
      driver: default
      config:
        - subnet: ${IP_NETWORK}

services:
  nginx:
    container_name: ${PREFIX}nginx${SUFFIX}
    hostname: ${PREFIX}nginx${SUFFIX}
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
      - "${SOCKET}:${SOCKET}"
    networks:
      linkt_net:
        ipv4_address: ${IP_NGINX}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - MYUSER=${MYUSER}
    volumes:
      - /home/${MYUSER}/${PROJECT}:/var/www
      - ../${VOLUME}/nginx:/var/log/nginx

  mariadb:
    container_name: ${PREFIX}mariadb${SUFFIX}
    hostname : ${PREFIX}mariadb${SUFFIX}
    image: mariadb:latest
    networks:
      linkt_net:
        ipv4_address: ${IP_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ../${VOLUME}/mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: ${PREFIX}phpmyadmin${SUFFIX}
    hostname : ${PREFIX}phpmyadmin${SUFFIX}
    image: phpmyadmin/phpmyadmin
    networks:
      linkt_net:
        ipv4_address: ${IP_PHP_MYADMIN}
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "/sessions"
    links:
      - "mariadb:db"

  sails_dev:
    container_name: ${PREFIX}sails${SUFFIX}
    hostname: ${PREFIX}sails${SUFFIX}
    build:
      context: .
      dockerfile: ./sails/Dockerfile
      args:
        - SAILS_VERSION=${SAILS_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    networks:
      linkt_net:
        ipv4_address: ${IP_SAILS}
    ports:
      - "${SAILS_PORT}:1337"
    environment:
      - NODE_ENV=dev
    volumes:
      - /home/${MYUSER}/sails:/server

  maildev:
    container_name: ${PREFIX}maildev${SUFFIX}
    hostname: ${PREFIX}maildev${SUFFIX}
    build:
      context: .
      dockerfile: ./maildev/Dockerfile
    networks:
      linkt_net:
        ipv4_address: ${IP_MAILDEV}
    ports:
      - "${SMTP}:25"
      - "${WEBUI}:80"

