version: '2.0'

volumes:
  portainer_data:

networks:
  linkt_network:
    ipam:
      driver: default
      config:
        - subnet: ${IP_NETWORK}

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    networks:
      linkt_network:
        ipv4_address: ${IP_PORTAINER}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mariadb:
    container_name: ${PREFIX}mariadb${SUFFIX}
    hostname : ${PREFIX}mariadb${SUFFIX}
    image: mariadb:latest
    networks:
      linkt_network:
        ipv4_address: ${IP_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ../${VOLUME}/mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: ${PREFIX}phpmyadmin${SUFFIX}
    hostname : ${PREFIX}phpmyadmin${SUFFIX}
    image: phpmyadmin/phpmyadmin
    networks:
      linkt_network:
        ipv4_address: ${IP_PHP_MYADMIN}
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "/sessions"
    links:
      - "mariadb:db"

  maildev:
    container_name: ${PREFIX}maildev${SUFFIX}
    hostname: ${PREFIX}maildev${SUFFIX}
    build:
      context: .
      dockerfile: ./maildev/Dockerfile
    networks:
      linkt_network:
        ipv4_address: ${IP_MAILDEV}
    ports:
      - "${SMTP}:25"
      - "${WEBUI}:80"


