version: '3'

volumes:
  portainer_data:

networks:
  linkt_net:
    ipam:
      driver: default
      config:
        - subnet: ${IP_NETWORK}

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    networks:
      linkt_net:
        ipv4_address: ${IP_PORTAINER}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:80"
      - "8083:443"
      - "${SOCKET}:${SOCKET}"
    networks:
      linkt_net:
        ipv4_address: ${IP_NGINX}
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - MYUSER=${MYUSER}
    volumes:
      - /home/${MYUSER}/site:/var/www
      - ../${VOLUME}/nginx:/var/log/nginx

  redis:
    container_name: redis
    hostname : redis
    image: redis
    networks:
      linkt_net:
        ipv4_address: ${IP_REDIS}
    ports:
      - "6379:6379"
    volumes:
      - ../${VOLUME}/redis:/data

  mariadb:
    container_name: mariadb
    hostname : mariadb
    image: mariadb:latest
    networks:
      linkt_net:
        ipv4_address: ${IP_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - "3306:3306"
    volumes:
      - ../${VOLUME}/mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    hostname : phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      linkt_net:
        ipv4_address: ${IP_PHP_MYADMIN}
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    restart: always
    ports:
      - "9090:80"
    volumes:
      - "/sessions"
    links:
      - "mariadb:db"

  sails_dev:
    container_name: sails
    hostname: sails
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        - SAILS_VERSION=${SAILS_VERSION}
    networks:
      linkt_net:
        ipv4_address: ${IP_SAILS}
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=dev
    command: "sails lift"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:10.1
    networks:
      linkt_net:
        ipv4_address: ${IP_POSTGRES}
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ../${VOLUME}/postgres:/var/lib/postgresql/data

  sonarqube:
    container_name: sonarqube
    hostname: sonarqube
    image: sonarqube:6.7.2
    networks:
      linkt_net:
        ipv4_address: ${IP_SONARQUBE}    
    ports:
      - "7000:9000"
      - "5432:5432"
    links:
      - postgres:db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
