version: '2.0'

volumes:
  portainer_data:

networks:
  linkt_net:
    ipam:
      driver: default
      config:
        - subnet: ${IP_NETWORK}

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    networks:
      linkt_net:
        ipv4_address: ${IP_PORTAINER}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
