version: '2.0'

volumes:
  portainer_data:

networks:
  linkt_network:
    external:
      name: docker_linkt_network

services:
  nginx:
    container_name: ${PREFIX}nginx${SUFFIX}
    hostname: ${PREFIX}nginx${SUFFIX}
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
      - "${SOCKET}:${SOCKET}"
    networks:
      linkt_network:
        ipv4_address: ${IP_NGINX}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - MYUSER=${MYUSER}
    volumes:
      - /home/${MYUSER}/${PROJECT}:/var/www
      - ../${VOLUME}/${PROJECT}/nginx:/var/log/nginx

  sails_dev:
    container_name: ${PREFIX}sails${SUFFIX}
    hostname: ${PREFIX}sails${SUFFIX}
    build:
      context: .
      dockerfile: ./sails/Dockerfile
      args:
        - SAILS_VERSION=${SAILS_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    networks:
      linkt_network:
        ipv4_address: ${IP_SAILS}
    ports:
      - "${SAILS_PORT}:1337"
    environment:
      - NODE_ENV=dev
    volumes:
      - /home/${MYUSER}/apierp:/server
